# Lab 1.02 - Android Persistence

Import all necessary Python libraries and create a variable `android_persistence` to load the dataset [android_persistence_cpu.csv](https://github.com/HoGentTIN/dsai-en-labs/blob/main/data/android_persistence_cpu.csv). See the [code book](https://github.com/HoGentTIN/dsai-en-labs/blob/main/data/android_persistence_cpu.md) for more info on the contents. Note this file is not stored as a regular CSV file! You may need to tweak the parameters of the import function to load the file correctly.

In [13]:
# Importing the necessary packages
import numpy as np                                  # "Scientific computing"
import scipy.stats as stats                         # Statistical tests

import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype

import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation

android_persistence = pd.read_csv("../data/android_persistence_cpu.csv", delimiter=";")

Explore the dataset:

- How many variables and observations are present in the dataset?
- What is the level of measurement of each variable?
- Perform the conversion of the qualitative variables to the appropriate type (and specify the order of ordinal variables).
- List the data types in the dataset.

In [26]:
android_persistence.head()

   Time    PersistenceType DataSize
0  1.81  Sharedpreferences    Small
1  1.35  Sharedpreferences    Small
2  1.84  Sharedpreferences    Small
3  1.54  Sharedpreferences    Small
4  1.81  Sharedpreferences    Small

In [32]:
# android_persistence.info()

# for i in android_persistence.columns:
#     print(android_persistence[i].describe)
#     print("-----")
#     # Time = Quantative (Ratio)
#     # PersistenceType = Qualitative (Nominal)
#     # Datasize = Qualitative (Oridinal)

# android_persistence.PersistenceType = android_persistence.PersistenceType.astype('category')
# android_persistence.DataSize = android_persistence.DataSize.astype(CategoricalDtype(categories=['Small', 'Medium', 'Large']))

android_persistence.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Time             300 non-null    float64
 1   PersistenceType  300 non-null    category
 2   DataSize         300 non-null    category
dtypes: category(2), float64(1)
memory usage: 3.2 KB

Describe each variable.

What unique values are there for the variables `PersistenceType` and `DataSize`? How often does each value occur?

In [ ]:
android_persistence.PersistenceType.unique()
android_persistence.Datasize.unique()

['Sharedpreferences', 'GreenDAO', 'SQLLite', 'Realm']
Categories (4, str): ['GreenDAO', 'Realm', 'SQLLite', 'Sharedpreferences']

In this dataset, it is especially interesting to know how often each unique combination of `PersistenceType` and `DataSize` occurs. Figure out how to use the Pandas function `crosstab()` to create a so-called contingency table for these variables. By the way, this concept will return in Module 4 (examining the relationship between 2 qualitative variables).

In [ ]:
pd.crosstab(android_persistence.PersistenceType, android_persistence.DataSize)

DataSize           Small  Medium  Large
PersistenceType
GreenDAO              30      30     30
Realm                 30      30     30
SQLLite               30      30     30
Sharedpreferences     30       0      0

: